name: teman_asa
description: Aplikasi pendukung orang tua dan anak dengan spektrum autisme.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.20.2

  # Ikon & Font
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  
  # Fitur Suara & Audio
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  youtube_player_flutter: ^9.0.1
  
  # Penyimpanan
  shared_preferences: ^2.2.2
  
  # --- FIREBASE & GOOGLE SIGN IN (Wajib Sejajar) ---
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: 6.2.1

  geolocator: ^14.0.2         # Untuk tahu lokasi GPS HP
  url_launcher: ^6.3.1        # Untuk buka Google Maps
  google_generative_ai: ^0.4.6
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NerkoOne
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf